"""empty message

Revision ID: 12b9a57a4f5d
Revises: 
Create Date: 2018-10-22 18:02:23.819704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b9a57a4f5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('auth_check', sa.Boolean(), nullable=False),
    sa.Column('only_root', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('listorder', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pid')
    )
    op.create_index(op.f('ix_user_pid'), 'user', ['pid'], unique=False)
    op.create_index(op.f('ix_user_rule'), 'user', ['rule'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_rule'), table_name='user')
    op.drop_index(op.f('ix_user_pid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
