"""empty message

Revision ID: d0e436752513
Revises: 5f180a13dfbf
Create Date: 2018-10-23 11:53:49.470410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e436752513'
down_revision = '5f180a13dfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_admin', sa.Column('gender', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_admin', 'gender')
    # ### end Alembic commands ###
