"""empty message

Revision ID: 1447cff80e60
Revises: d138d82ddb94
Create Date: 2018-11-07 15:11:33.437865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1447cff80e60'
down_revision = 'd138d82ddb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_starsector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('shipclass', sa.String(length=30), nullable=False),
    sa.Column('force', sa.String(length=30), nullable=False),
    sa.Column('pic_address', sa.String(length=100), nullable=False),
    sa.Column('listorder', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_starsector_listorder'), 'data_starsector', ['listorder'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_starsector_listorder'), table_name='data_starsector')
    op.drop_table('data_starsector')
    # ### end Alembic commands ###
