"""empty message

Revision ID: 6e6068157db4
Revises: 1447cff80e60
Create Date: 2018-11-09 10:09:06.469512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e6068157db4'
down_revision = '1447cff80e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bx_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bxname', sa.String(length=30), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('coverage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bx_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=False),
    sa.Column('bx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bx_id'], ['bx_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bx_keys')
    op.drop_table('bx_list')
    # ### end Alembic commands ###
