"""empty message

Revision ID: 7c71379a2af2
Revises: 6e6068157db4
Create Date: 2018-11-09 15:41:04.571762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c71379a2af2'
down_revision = '6e6068157db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_rule', sa.Column('pagedesc', sa.String(length=120), nullable=False))
    op.add_column('auth_rule', sa.Column('pagetitle', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_auth_rule_pagedesc'), 'auth_rule', ['pagedesc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_rule_pagedesc'), table_name='auth_rule')
    op.drop_column('auth_rule', 'pagetitle')
    op.drop_column('auth_rule', 'pagedesc')
    # ### end Alembic commands ###
