"""empty message

Revision ID: a8bfe20ef311
Revises: d0e436752513
Create Date: 2018-10-23 17:22:49.782492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bfe20ef311'
down_revision = 'd0e436752513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_starsector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('shipclass', sa.String(length=30), nullable=False),
    sa.Column('force', sa.String(length=30), nullable=False),
    sa.Column('pic_address', sa.String(length=100), nullable=False),
    sa.Column('listorder', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_starsector_listorder'), 'data_starsector', ['listorder'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_starsector_listorder'), table_name='data_starsector')
    op.drop_table('data_starsector')
    # ### end Alembic commands ###
