"""empty message

Revision ID: c3486514d162
Revises: 12b9a57a4f5d
Create Date: 2018-10-22 18:03:19.178871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3486514d162'
down_revision = '12b9a57a4f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('rule', sa.String(length=100), nullable=False),
    sa.Column('auth_check', sa.Boolean(), nullable=False),
    sa.Column('only_root', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('listorder', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pid')
    )
    op.create_index(op.f('ix_auth_rule_pid'), 'auth_rule', ['pid'], unique=False)
    op.create_index(op.f('ix_auth_rule_rule'), 'auth_rule', ['rule'], unique=False)
    op.drop_index('ix_user_pid', table_name='user')
    op.drop_index('ix_user_rule', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('rule', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('auth_check', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('only_root', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('listorder', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'pid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_rule', 'user', ['rule'], unique=False)
    op.create_index('ix_user_pid', 'user', ['pid'], unique=False)
    op.drop_index(op.f('ix_auth_rule_rule'), table_name='auth_rule')
    op.drop_index(op.f('ix_auth_rule_pid'), table_name='auth_rule')
    op.drop_table('auth_rule')
    # ### end Alembic commands ###
